import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { ArrowRight, Check, Copy, Flag, Heart, MessageCircle, Search, Shield, Swords, Trophy, UserPlus, Users } from 'lucide-react';
import { SocialService, type DirectChallenge, type Friendship, type SocialComment, type SocialProfile, type SocialViewer, type SquadActivity } from './product/socialService';
import { LeagueService, LEAGUE_TIERS, type LeagueMember } from './product/leagueService';
import { explainError, type Profile } from './state';
import { Tiger } from './Visual';

export default function Community({ profile, preview }: { profile: Profile; preview: boolean }) {
  const [tab, setTab] = useState('friends'), [friends, setFriends] = useState<Friendship[]>([]), [requests, setRequests] = useState<Friendship[]>([]), [feed, setFeed] = useState<SquadActivity[]>([]), [league, setLeague] = useState<LeagueMember[]>([]), [challenges, setChallenges] = useState<DirectChallenge[]>([]);
  const [search, setSearch] = useState(''), [results, setResults] = useState<SocialProfile[]>([]), [searchDone, setSearchDone] = useState(false), [busy, setBusy] = useState(''), [error, setError] = useState(''), [status, setStatus] = useState(''), [blocked, setBlocked] = useState(() => SocialService.getBlockedUserIds(profile.uid));
  const [loadErrors,setLoadErrors] = useState<Record<string,string>>({});
  const viewer = useMemo<SocialViewer>(() => ({ uid: profile.uid, displayName: profile.displayName || 'T1GER learner', photoURL: profile.photoURL, weeklyXP: profile.weeklyXP, verifiedXP: profile.verifiedXP, currentWeekId: profile.currentWeekId, leagueTier: profile.leagueTier, streak: profile.streak }), [profile.uid, profile.displayName, profile.photoURL, profile.weeklyXP, profile.verifiedXP, profile.currentWeekId, profile.leagueTier, profile.streak]);
  useEffect(() => {
    const failed=(feature:string)=>(cause:Error)=>{const code='code' in cause?String(cause.code):'unknown';console.warn('[T1GER community]',feature,code);setLoadErrors(previous=>({...previous,[feature]:feature+' could not load. Reload to reconnect.'}));};
    const recovered=(feature:string)=>setLoadErrors(previous=>{const next={...previous};delete next[feature];return next;});
    const stops=[SocialService.subscribeBlocked(viewer.uid,next=>{setBlocked(next);recovered('Safety controls');},failed('Safety controls')),SocialService.subscribeFriends(viewer.uid,(next,pending)=>{setFriends(next);setRequests(pending);recovered('Friends');},failed('Friends')),SocialService.subscribeActivityFeed(viewer.uid,next=>{setFeed(next);recovered('Activity');},failed('Activity')),SocialService.subscribeLeague(viewer,next=>{setLeague(next);recovered('League');},failed('League')),SocialService.subscribeChallenges(viewer.uid,next=>{setChallenges(next);recovered('Challenges');},failed('Challenges'))];
    return()=>stops.forEach(stop=>stop());
  },[viewer]);
  useEffect(() => { let invited = new URLSearchParams(window.location.search).get('invite'); try { invited ||= sessionStorage.getItem('t1ger-pending-invite'); } catch { /* Use the URL invitation. */ } if (!invited || invited === viewer.uid || preview) return; let active = true; SocialService.getProfile(invited).then(found => { if (active && found) { setResults([found]); setSearchDone(true); } }).catch(() => { if (active) setError('This invitation could not load. Try the invitation code instead.'); }); return () => { active = false; }; }, [viewer.uid, preview]);
  async function act(id: string, action: () => Promise<unknown>, success: string) {
    if (busy) return; setBusy(id); setError(''); setStatus('');
    try { await action(); setStatus(success); } catch (cause) { setError(explainError(cause, 'Could not complete that action. Please try again.')); } finally { setBusy(''); }
  }
  const tier = LeagueService.normalizeTier(profile.leagueTier) || LeagueService.getUserTier(profile.verifiedXP || 0);
  const safeFriends = friends.filter(item => !blocked.includes(item.profile.uid));
  async function searchPeople(event: FormEvent) { event.preventDefault(); await act('search', async () => { const found = await SocialService.searchProfiles(search, profile.uid); setResults(found.filter(item => !blocked.includes(item.uid))); setSearchDone(true); }, ''); }
  return <div className="page community-page"><header className="page-top"><p className="eyebrow">Community</p><h1>Better together.<br/><span className="soft-heading">At your own pace.</span></h1><p className="muted">A little encouragement. Shared curiosity. Progress that’s yours.</p></header><div className="community-tabs" role="tablist" aria-label="Community sections">{[{ id: 'friends', label: 'Friends', icon: Users }, { id: 'feed', label: 'Activity', icon: Heart }, { id: 'league', label: 'League', icon: Trophy }, { id: 'challenges', label: 'Challenges', icon: Swords }].map(item => <button key={item.id} role="tab" aria-selected={tab === item.id} aria-controls={`community-${item.id}`} id={`community-tab-${item.id}`} onClick={() => setTab(item.id)}><item.icon size={18}/>{item.label}</button>)}</div>
    {Object.values(loadErrors).map(message=><p className="error" role="alert" key={message}>{message}</p>)}{error && <p className="error" role="alert">{error}</p>}{status && <p className="community-status" role="status">{status}</p>}
    <section id={`community-${tab}`} role="tabpanel" aria-labelledby={`community-tab-${tab}`}>
    {tab === 'friends' && <><div className="community-intro"><div><h2>Find your people.</h2><p>Search by username or invitation code. Your email stays private.</p></div><button className="button subtle" disabled={!!busy || preview} onClick={() => act('profile', () => SocialService.ensurePublicSocialProfile(viewer), 'Your community profile is ready.')}><UserPlus size={18}/>Set up community profile</button></div><form className="community-search" onSubmit={searchPeople}><label className="sr-only" htmlFor="friend-search">Find a friend</label><input id="friend-search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Username or invitation code" maxLength={60}/><button className="button primary" disabled={search.trim().length < 2 || !!busy}><Search size={18}/>Search</button></form><div className="invite-line"><span>Your code <strong>{SocialService.getInviteCode(profile.uid)}</strong></span><button className="text-link" onClick={() => act('copy', () => SocialService.copyInviteLink(profile.uid), 'Invitation link copied.')}><Copy size={16}/>Copy invitation</button></div>
      {searchDone && <section className="community-results"><h3>Search results</h3>{results.length ? results.map(person => <div className="person-row" key={person.uid}><span className="person-avatar">{person.displayName.charAt(0)}</span><div><strong>{person.displayName}</strong><small>@{person.username}</small></div><button className="button subtle" disabled={!!busy || safeFriends.some(item => item.profile.uid === person.uid)} onClick={() => act(person.uid, () => SocialService.sendFriendRequest(profile.uid, person.uid), 'Friend request sent.')}><UserPlus size={17}/>{safeFriends.some(item => item.profile.uid === person.uid) ? 'Friends' : 'Add friend'}</button></div>) : <p className="muted">No match. Try their exact invitation code.</p>}</section>}
      {requests.length > 0 && <section className="friend-requests"><h3>Friend requests</h3>{requests.map(request => <div className="person-row" key={request.id}><span className="person-avatar">{request.profile.displayName.charAt(0)}</span><strong>{request.profile.displayName}</strong><button disabled={!!busy} className="button primary" onClick={() => act(request.id, () => SocialService.acceptFriendRequest(request.id, profile.uid), 'Friend request accepted.')}><Check size={16}/>Accept</button><button disabled={!!busy} className="button subtle" onClick={() => act(request.id, () => SocialService.declineFriendRequest(request.id, profile.uid), 'Friend request declined.')}>Decline</button></div>)}</section>}
      {safeFriends.length ? <div className="friends-grid">{safeFriends.map(friend => <article className="friend-card" key={friend.id}><span className="person-avatar">{friend.profile.displayName.charAt(0)}</span><h3>{friend.profile.displayName}</h3><p>{friend.profile.streak} day streak</p><button className="button subtle" disabled={!!busy} onClick={() => act(friend.id, () => SocialService.createChallenge(viewer, friend.profile, 7, 0), 'Seven-day challenge sent.')}><Swords size={17}/>Challenge</button><button className="text-link" disabled title="Mobile push delivery is awaiting provider configuration">Encouragement · coming soon <ArrowRight size={16}/></button><details><summary>Safety controls</summary><button disabled={!!busy} onClick={() => act(`block-${friend.id}`, async () => { await SocialService.blockUser(profile.uid, friend.profile.uid); setBlocked(SocialService.getBlockedUserIds(profile.uid)); }, 'User blocked.')}><Shield size={16}/>Block user</button><button disabled={!!busy} onClick={() => act(`report-${friend.id}`, () => SocialService.reportUser(profile.uid, friend.profile.uid, 'other'), 'Report submitted for review.')}><Flag size={16}/>Report user</button></details></article>)}</div> : <div className="editorial-empty"><Users size={42}/><h2>Good company starts with hello.</h2><p>Invite a friend to learn alongside you. Requests and shared activity will appear here.</p></div>}
      {blocked.length > 0 && <details className="blocked-list"><summary>Blocked accounts ({blocked.length})</summary>{blocked.map(id => <button className="button subtle" key={id} disabled={!!busy} onClick={() => act(`unblock-${id}`, async () => { await SocialService.unblockUser(profile.uid, id); setBlocked(SocialService.getBlockedUserIds(profile.uid)); }, 'Account unblocked.')}>Unblock {id.slice(0, 8)}</button>)}</details>}</>}
    {tab === 'feed' && (feed.length ? <div className="activity-feed">{feed.filter(item => !blocked.includes(item.userId)).map(activity => <Activity key={`${activity.circleId}-${activity.id}`} activity={activity} viewer={viewer} act={act} busy={busy}/>)}</div> : <div className="editorial-empty"><Tiger animation="idle"/><h2>Your next shared moment.</h2><p>Once you join a squad, its learning activity appears here.</p><button className="button primary" onClick={() => setTab('friends')}>Find a friend <ArrowRight size={18}/></button></div>)}
    {tab === 'league' && <><div className="league-intro"><span className="league-emblem"><Trophy size={42}/></span><div><p className="eyebrow">{LEAGUE_TIERS[tier].nameEn}</p><h2>Steady effort. Shared momentum.</h2><p>Verified learning XP in your weekly group. Self-reported Apply and focus time do not affect league position.</p><span className="small-copy">Week ends in {LeagueService.getTimeRemaining().formatted}</span></div></div><ol className="league-list">{league.map((member, index) => <li className={member.isCurrentUser ? 'current-user' : ''} key={member.id}><span>{index + 1}</span><span className="person-avatar">{member.name.charAt(0)}</span><strong>{member.name}{member.isCurrentUser ? ' · You' : ''}</strong><span>{member.vXP} XP</span></li>)}</ol>{league.length <= 1 && <p className="muted">Your group is quiet right now. Real members appear as they join this cohort.</p>}</>}
    {tab === 'challenges' && (challenges.length ? <div className="challenge-list">{challenges.map(challenge => <article key={challenge.id}><Swords size={28}/><h2>{challenge.senderName} & {challenge.receiverName}</h2><p>{challenge.durationDays} days · {challenge.metric} · {challenge.status}</p><div className="challenge-scores"><strong>{challenge.senderScore}</strong><span>—</span><strong>{challenge.receiverScore}</strong></div>{challenge.status === 'pending' && challenge.receiverId === profile.uid && <div><button className="button primary" disabled={!!busy} onClick={() => act(challenge.id, () => SocialService.acceptChallenge(challenge.id, profile.uid), 'Challenge accepted.')}>Accept challenge</button><button className="button subtle" disabled={!!busy} onClick={() => act(challenge.id, () => SocialService.declineChallenge(challenge.id, profile.uid), 'Challenge declined.')}>Decline</button></div>}</article>)}</div> : <div className="editorial-empty"><Swords size={42}/><h2>A friendly reason to show up.</h2><p>Start a seven-day challenge with a friend. Only server-verified missions count. New Web challenges carry no coin stake.</p><button className="button primary" onClick={() => setTab('friends')}>Choose a friend <ArrowRight size={18}/></button></div>)}
    </section></div>;
}

function Activity({ activity, viewer, act, busy }: { activity: SquadActivity; viewer: SocialViewer; act: (id: string, action: () => Promise<unknown>, success: string) => Promise<void>; busy: string }) {
  const [showComments, setShowComments] = useState(false), [comments, setComments] = useState<SocialComment[]>([]), [draft, setDraft] = useState(''), [commentError,setCommentError] = useState('');
  useEffect(() => { if (!showComments) return; return SocialService.subscribeComments(activity, setComments, () => setCommentError('Comments could not load. Close and reopen to reconnect.')); }, [activity, showComments]);
  return <article className="activity-card"><div className="person-row"><span className="person-avatar">{activity.userName.charAt(0)}</span><strong>{activity.userName}</strong><small>{new Date(activity.createdAt).toLocaleDateString()}</small></div><h2>{activity.missionTitle}</h2><p>{activity.verified ? 'Verified learning' : 'Personal practice'} · {activity.durationMinutes} min</p><div className="activity-actions"><button className="button subtle" disabled={!!busy} aria-pressed={activity.myReactions.includes('respect')} onClick={() => act(`react-${activity.id}`, () => SocialService.reactToActivity(activity, viewer.uid, 'respect', !activity.myReactions.includes('respect')), '')}><Heart size={17}/>{activity.reactionCounts.respect || 0}</button><button className="button subtle" onClick={() => setShowComments(!showComments)}><MessageCircle size={17}/>{activity.commentCount} comments</button></div>{showComments && <div className="activity-comments">{commentError && <p className="error" role="alert">{commentError}</p>}{comments.map(comment => <p key={comment.id}><strong>{comment.userName}</strong> {comment.body}</p>)}<form onSubmit={event => { event.preventDefault(); void act(`comment-${activity.id}`, async () => { await SocialService.addComment(activity, viewer.uid, viewer.displayName, draft); setDraft(''); }, 'Comment posted.'); }}><label className="sr-only" htmlFor={`comment-${activity.id}`}>Your comment</label><input id={`comment-${activity.id}`} value={draft} maxLength={280} placeholder="A little encouragement…" onChange={event => setDraft(event.target.value)}/><button className="button primary" disabled={!!busy || !draft.trim()}>Post</button></form></div>}</article>;
}
