import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Award, Bell, BookOpen, Check, Clock, Coffee, Library, MessageCircle, Pause, Play, RotateCcw, Settings, Target, Users } from 'lucide-react';
import { collection, getDocs, limit, orderBy, query } from 'firebase/firestore';
import { db } from './firebase';
import { brainOf, explainError, type Mission, type Profile } from './state';
import type { InteractiveTrack } from './product/interactiveCurriculumTypes';
import { appliedLessonIds, focusRemaining } from './product/webProgress';
import { saveFocus, savePreferences, saveReflection } from './companionData';
import { Tiger } from './Visual';
import Companion from './Companion';
import LearningMomentum from './LearningMomentum';
import { learningRhythm } from './product/learningRhythm';
import AnalyticsPreferences from '../../../src/components/analytics/AnalyticsPreferences';

export const companionLinks = [
  { id:'companion', title:'Your companion', detail:'A little tiger. Earned accessories. Your learning rhythm.', icon:Award, tone:'orange' },
  { id: 'coach', title: 'AI mentor', detail: 'A little guidance for your next big question.', icon: MessageCircle, tone: 'violet' },
  { id: 'community', title: 'Community', detail: 'Friends, shared progress and weekly leagues.', icon: Users, tone: 'blue' },
  { id: 'library', title: 'Your collection', detail: 'Useful tools. Decisions worth keeping.', icon: Library, tone: 'mint' },
  { id: 'focus', title: 'Focus', detail: 'Make a little space for what matters.', icon: Clock, tone: 'orange' },
  { id: 'progress', title: 'Your progress', detail: 'Small steps add up. See your week.', icon: Award, tone: 'yellow' },
  { id: 'settings', title: 'Settings', detail: 'Your pace, preferences and reminders.', icon: Settings, tone: 'neutral' },
];
type ToolProps = { profile: Profile; missions: Mission[]; paths: InteractiveTrack[]; preview: boolean; go: (path: string) => void };

export default function CompanionTools({ destination, ...props }: ToolProps & { destination: string }) {
  if (destination === 'companion') return <Companion profile={props.profile} preview={props.preview} go={props.go}/>;
  if (destination === 'library') return <Collection {...props}/>;
  if (destination === 'focus') return <Focus profile={props.profile} preview={props.preview}/>;
  if (destination === 'progress') return <Progress {...props}/>;
  if (destination === 'settings') return <Preferences profile={props.profile} preview={props.preview}/>;
  return <div className="page more-page"><header className="page-top"><p className="eyebrow">Made for your curiosity</p><h1>Your learning space.</h1><p className="muted">Everything that supports your learning, in one place.</p></header><div className="feature-grid">{companionLinks.map(item => <button className={`feature-card ${item.tone}`} key={item.id} onClick={() => props.go(`/${item.id}`)}><span className="feature-icon"><item.icon size={28}/></span><h2>{item.title}</h2><p>{item.detail}</p><ArrowRight size={22}/></button>)}<button className="feature-card neutral" onClick={() => props.go('/profile')}><span className="feature-icon"><Settings size={28}/></span><h2>Your account</h2><p>Your profile, membership and account controls.</p><ArrowRight size={22}/></button></div></div>;
}

function Collection({ profile, paths, go }: ToolProps) {
  const [search, setSearch] = useState('');
  const artifacts = (profile.learningArtifacts || []).filter(item => `${item.title} ${item.summary}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="page collection-page"><header className="page-top"><p className="eyebrow">Your collection</p><h1>Your saved tools.</h1><p className="muted">The prompts, plans and decisions you’ve made along the way.</p></header><label className="search-field">Find a saved tool<input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search your collection"/></label>{artifacts.length ? <div className="collection-grid">{artifacts.map(item => <article className="collection-card" key={item.lessonId}><Library size={26}/><p className="eyebrow">{paths.flatMap(path => path.lessons).find(lesson => lesson.id === item.lessonId)?.title.en || 'Your learning tool'}</p><h2>{item.title}</h2><p className="saved-summary">{item.summary}</p><button className="text-link" onClick={() => go(`/lesson/${item.lessonId}`)}>Revisit lesson <ArrowRight size={17}/></button></article>)}</div> : <div className="editorial-empty"><Library size={44}/><h2>{search ? 'No matching tools yet.' : 'Your first useful tool is ahead.'}</h2><p>{search ? 'Try a different word.' : 'Save a tool in Apply and it will appear here, across your devices.'}</p>{search && <button className="button subtle" onClick={() => setSearch('')}>Clear search</button>}{!search && <button className="button primary" onClick={() => go('/learn')}>Start learning <ArrowRight size={18}/></button>}</div>}</div>;
}

function Focus({ profile, preview }: Pick<ToolProps, 'profile' | 'preview'>) {
  const storageKey = 't1ger-focus-' + (preview ? 'preview' : profile.uid);
  const [initial] = useState(() => { try { const value = JSON.parse(localStorage.getItem(storageKey) || 'null'); if (value && [5,25,50].includes(value.duration) && Number.isFinite(value.paused) && value.paused >= 0 && value.paused <= value.duration * 60 && (value.deadline === null || Number.isFinite(value.deadline)) && typeof value.sessionId === 'string') return value; } catch { /* Ignore an invalid local timer. */ } return { duration:25, paused:1500, deadline:null, breakMode:false, saved:false, sessionId:'focus-'+Date.now() }; });
  const [duration, setDuration] = useState<number>(initial.duration);
  const [paused, setPaused] = useState<number>(initial.paused);
  const [deadline, setDeadline] = useState<number | null>(initial.deadline);
  const [now, setNow] = useState(Date.now);
  const [breakMode, setBreakMode] = useState<boolean>(!!initial.breakMode);
  const [saved, setSaved] = useState<boolean>(!!initial.saved);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const sessionId = useRef<string>(initial.sessionId);
  const remaining = focusRemaining(deadline, paused, now);
  const finished = remaining === 0;
  useEffect(() => { if (deadline === null || finished) return; const timer = window.setInterval(() => setNow(Date.now()), 250); const resume = () => setNow(Date.now()); window.addEventListener('focus', resume); return () => { window.clearInterval(timer); window.removeEventListener('focus', resume); }; }, [deadline, finished]);
  useEffect(() => { try { localStorage.setItem(storageKey, JSON.stringify({ duration, paused, deadline, breakMode, saved, sessionId:sessionId.current })); } catch { /* The running timer still works without local persistence. */ } }, [storageKey, duration, paused, deadline, breakMode, saved]);
  function reset(minutes: number, rest = false) { setDeadline(null); setPaused(minutes * 60); setDuration(minutes); setBreakMode(rest); setNow(Date.now()); setSaved(false); setError(''); sessionId.current = `focus-${Date.now()}`; }
  async function finish() { if (remaining !== 0 || busy || saved || breakMode) return; if (preview) { setSaved(true); return; } setBusy(true); try { await saveFocus(profile.uid, sessionId.current, duration); setSaved(true); } catch (cause) { setError(explainError(cause, 'Could not save your focus session. Try again.')); } finally { setBusy(false); } }
  return <div className="page focus-page"><header className="page-top"><p className="eyebrow">Focus</p><h1>One thing.<br/><span className="soft-heading">Your full attention.</span></h1><p className="muted">A quiet moment to learn, apply or simply think.</p></header><section className="focus-canvas"><div className="focus-options" aria-label="Session length">{[5, 25, 50].map(minutes => <button disabled={deadline !== null || busy} aria-pressed={!breakMode && duration === minutes} onClick={() => reset(minutes)} key={minutes}>{minutes} min</button>)}</div><div className={`focus-ring ${remaining === 0 ? 'finished' : ''}`} style={{ '--focus-progress': `${(1 - remaining / (duration * 60)) * 360}deg` } as React.CSSProperties}><div><span>{breakMode ? 'Take a breath' : remaining === 0 ? 'Nicely done' : 'Stay with it'}</span><strong role="timer" aria-label="Time remaining">{String(Math.floor(remaining / 60)).padStart(2, '0')}:{String(remaining % 60).padStart(2, '0')}</strong><span>{breakMode ? 'Rest is part of the rhythm.' : 'No rush. Just a little intention.'}</span></div></div><div className="focus-controls"><button className="icon-button" disabled={busy} aria-label="Reset focus timer" onClick={() => reset(duration, breakMode)}><RotateCcw size={19}/></button>{remaining > 0 && <button className="button primary" onClick={() => { const clock = Date.now(); setNow(clock); if (deadline !== null) { setPaused(focusRemaining(deadline, paused, clock)); setDeadline(null); } else setDeadline(clock + paused * 1000); }}>{deadline !== null ? <><Pause size={18}/>Pause</> : <><Play size={18}/>Start focus</>}</button>}{remaining === 0 && !breakMode && <button className="button primary" disabled={busy || saved} onClick={finish}>{saved ? <><Check size={18}/>{preview ? 'Preview complete' : 'Session saved'}</> : busy ? 'Saving…' : 'Save focus session'}</button>}<button className="button subtle" disabled={busy} onClick={() => reset(5, true)}><Coffee size={18}/>Take a break</button></div><p className="small-copy">{preview ? 'Design preview. Focus is not saved.' : 'Focus minutes are personal practice. They do not award competitive XP.'}</p>{error && <p className="error" role="alert">{error}</p>}{remaining === 0 && <Tiger animation="saved"/>}</section></div>;
}

function Progress({ profile, missions, paths, preview, go }: ToolProps) {
  const brain = brainOf(profile), done = appliedLessonIds(brain, missions);
  const rhythm = learningRhythm(profile, missions);
  const badges = [{ id: 'first_blood', name: 'First concept', detail: 'Your first learning step.', unlocked: brain.missionHistory.some(item => item.completed) }, { id: 'streak_3', name: 'Finding your rhythm', detail: 'A three-day learning streak.', unlocked: Math.max(profile.streak || 0, brain.learnStreak || 0) >= 3 }, { id: 'streak_7', name: 'A week of curiosity', detail: 'Seven days of showing up.', unlocked: Math.max(profile.streak || 0, brain.learnStreak || 0) >= 7 }, { id: 'rich_kid', name: 'Capital builder', detail: '10,000 earned coins.', unlocked: (profile.coins || 0) >= 10000 }];
  const [reflection, setReflection] = useState(''); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState('');
  const [past, setPast] = useState<{ id: string; reflection: string }[]>([]);
  useEffect(() => { if (preview || !db) return; let active = true; getDocs(query(collection(db, 'users', profile.uid, 'dailyQuestions'), orderBy('timestamp', 'desc'), limit(30))).then(snapshot => { if (active) setPast(snapshot.docs.filter(item => item.data().type === 'web-reflection').map(item => ({ id: item.id, reflection: String(item.data().reflection || '') }))); }).catch(() => { if (active) setError('Your saved reflections could not load. Try again later.'); }); return () => { active = false; }; }, [profile.uid, preview]);
  return <div className="page progress-page"><header className="page-top"><p className="eyebrow">Your progress</p><h1>Little by little.<br/><span className="soft-heading">Look how far.</span></h1><p className="muted">A record of the ideas you’ve made your own.</p></header><div className="metric-strip"><div><strong>{done.size}</strong><span>ideas applied</span></div><div><strong>{rhythm.streak}</strong><span>day streak</span></div><div><strong>{profile.xp || 0}</strong><span>learning XP</span></div><div><strong>{rhythm.activeDays}</strong><span>Apply days · last 7</span></div></div><LearningMomentum profile={profile} missions={missions} savedTools={profile.learningArtifacts?.length || 0} dueCount={Object.values(brain.fsrsCards || {}).filter(card => new Date(card.due).getTime() <= Date.now()).length} go={go}/><section className="progress-paths"><h2>Your paths</h2>{paths.map(path => <button key={path.id} onClick={() => go('/discover')} className="progress-path-row"><BookOpen size={24}/><div><strong>{path.title.en}</strong><progress value={path.lessons.filter(item => done.has(item.id)).length} max={path.lessons.length} aria-label={`${path.title.en} progress`}/></div><span>{path.lessons.filter(item => done.has(item.id)).length}/{path.lessons.length}</span><ArrowRight size={18}/></button>)}</section><section className="achievement-section"><h2>Moments worth keeping.</h2><div className="badge-grid">{badges.map(badge => <article key={badge.id} className={`achievement ${badge.unlocked || profile.unlockedAchievements?.includes(badge.id) ? 'unlocked' : ''}`}><Award size={32}/><h3>{badge.name}</h3><p>{badge.detail}</p><small>{badge.unlocked || profile.unlockedAchievements?.includes(badge.id) ? 'Achieved' : 'Still ahead'}</small></article>)}</div></section><section className="reflection-card"><div><span className="editorial-icon"><Target size={24}/></span><h2>Make today stick.</h2><p>What did you learn — and where could you use it?</p></div><div><label htmlFor="daily-reflection">Your reflection</label><textarea id="daily-reflection" value={reflection} onChange={event => { setReflection(event.target.value); setSaved(false); }} rows={4} maxLength={2000} placeholder="One idea. One next step."/><button className="button primary" disabled={reflection.trim().length < 10 || saving || saved} onClick={async () => { setSaving(true); setError(''); try { if (!preview) await saveReflection(profile.uid, `reflection-${Date.now()}`, reflection); setSaved(true); } catch (cause) { setError(explainError(cause, 'Could not save your reflection. Try again.')); } finally { setSaving(false); } }}>{saving ? 'Saving…' : saved ? preview ? 'Preview complete' : 'Reflection saved' : 'Save reflection'}</button>{error && <p className="error" role="alert">{error}</p>}</div></section>{past.length > 0 && <section className="past-reflections"><h2>Your earlier reflections</h2>{past.slice(0, 5).map(item => <blockquote key={item.id}>{item.reflection}</blockquote>)}</section>}</div>;
}

const reminderNames: Record<string, string> = { daily_reminder: 'Daily lesson', streak_risk: 'Streak reminder', streak_lost: 'A fresh start', streak_milestones: 'Streak milestones', level_up: 'Level up', apply_reminder: 'Finish Apply', action_completed: 'Applied ideas', weekly_summary: 'Weekly summary', leaderboard_drop: 'League movement', re_engagement: 'Return to learning', onboarding_nudge: 'Getting started' };
function Preferences({ profile, preview }: Pick<ToolProps, 'profile' | 'preview'>) {
  const [name, setName] = useState(profile.displayName || ''); const [pace, setPace] = useState(profile.dailyTime || 10); const [prefs, setPrefs] = useState(profile.notificationPreferences || {}); const [weekly, setWeekly] = useState(profile.weeklyReportOptIn || false);
  const [busy, setBusy] = useState(false), [status, setStatus] = useState(''), [error, setError] = useState('');
  return <div className="page preferences-page"><header className="page-top"><p className="eyebrow">Settings</p><h1>Your learning.<br/><span className="soft-heading">Your rhythm.</span></h1><p className="muted">A pace that fits your life. A little help when you want it.</p></header><section className="settings-section analytics-settings"><Settings size={24}/><h2>Your privacy choices.</h2><p>Choose whether to share optional, masked usage insights.</p><AnalyticsPreferences/></section><form className="preferences-form" onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); setStatus(''); try { if (!preview) await savePreferences(profile.uid, { displayName: name, dailyTime: pace, notificationPreferences: prefs, weeklyReportOptIn: weekly }); setStatus(preview ? 'Preview only. Preferences are not saved.' : 'Your preferences are saved.'); } catch (cause) { setError(explainError(cause, 'Could not save your preferences. Try again.')); } finally { setBusy(false); } }}><section className="settings-section"><Settings size={24}/><h2>The basics</h2><label htmlFor="learner-name">What should we call you?</label><input id="learner-name" value={name} maxLength={60} required onChange={event => setName(event.target.value)}/><label htmlFor="daily-pace">Daily intention</label><select id="daily-pace" value={pace} onChange={event => setPace(Number(event.target.value))}>{[5,10,15,20].map(minutes => <option value={minutes} key={minutes}>{minutes} minutes</option>)}</select></section><section className="settings-section"><Bell size={24}/><h2>A thoughtful nudge.</h2><p>These preferences sync with your mobile account. Browser push delivery is not active.</p>{Object.entries(reminderNames).map(([id, label]) => <label className="preference-toggle" key={id}><span>{label}</span><input type="checkbox" checked={prefs[id] ?? true} onChange={event => setPrefs({ ...prefs, [id]: event.target.checked })}/></label>)}<label className="preference-toggle"><span>Weekly report email</span><input type="checkbox" checked={weekly} onChange={event => setWeekly(event.target.checked)}/></label></section><button className="button primary" disabled={busy || !name.trim()}>{busy ? 'Saving…' : 'Save preferences'} <Check size={18}/></button>{status && <p role="status">{status}</p>}{error && <p className="error" role="alert">{error}</p>}</form></div>;
}
