import type { ReactNode } from 'react';
import { appHref } from './basePath';

const operator = import.meta.env.VITE_LEGAL_OPERATOR?.trim();
export const legalContactEmail = import.meta.env.VITE_LEGAL_CONTACT_EMAIL?.trim() || 'este.t1ger.oficial.app@gmail.com';
const contact = legalContactEmail;
const location = import.meta.env.VITE_LEGAL_LOCATION?.trim() || 'Plymouth, Michigan, United States (full postal address pending confirmation)';
const effectiveDate = import.meta.env.VITE_LEGAL_EFFECTIVE_DATE?.trim();

// Legal publication requires review of the real operator, data practices and jurisdictions.
export const legalDraft = !operator || !import.meta.env.VITE_LEGAL_LOCATION?.trim() || !effectiveDate || import.meta.env.VITE_LEGAL_PUBLISHED !== 'true';

function Contact() {
  return <>{operator || '[Legal operator to be confirmed]'}{location && <> · {location}</>}{contact ? <> · <a href={`mailto:${contact}`}>{contact}</a></> : <> · [Privacy contact to be confirmed]</>}</>;
}

export default function LegalPage({ kind, themeAction }: { kind: 'privacy' | 'terms'; themeAction?: ReactNode }) {
  const privacy = kind === 'privacy';
  return <main className="legal-page"><header className="legal-head"><a className="brand" href={appHref('/')}><span className="brand-mark">1</span><span>T1GER</span></a><div className="legal-actions"><nav aria-label="Legal pages"><a href={appHref('/privacy')} aria-current={privacy ? 'page' : undefined}>Privacy</a><a href={appHref('/terms')} aria-current={!privacy ? 'page' : undefined}>Terms</a></nav>{themeAction}</div></header>
    <article className="legal-content"><p className="eyebrow">T1GER / {privacy ? 'PRIVACY' : 'TERMS'}</p><h1>{privacy ? 'Privacy notice' : 'Terms of use'}</h1>
      {legalDraft && <div className="legal-draft" role="status"><strong>Draft for product review.</strong> The legal operator, full postal address, retention schedule and requirements for learners aged 15–17 must be confirmed before public release. This page is not a final legal notice.</div>}
      <p className="legal-updated">{effectiveDate ? `Effective ${effectiveDate}` : 'Effective date to be confirmed'} · Operator: <Contact/></p>
      {privacy ? <>
        <section><h2>What this web app handles</h2><p>To create and use an account, T1GER handles your email address, account identifier and the name you choose to provide. Sign-in with Google may provide basic account details. The app stores learning path, lesson and review progress, Apply submissions and reflections, and any simulation rules you save. Focus records, notification preferences, community profiles, friendship requests, shared activity, safety reports and your private blocked-account list support the optional companion features. Some lesson artifacts are also kept in this browser’s local storage.</p></section>
        <section><h2>Why and where</h2><p>These details support authentication, learning progress across web and mobile, review scheduling, saved exercises, account support and security. The web code uses Firebase Authentication, Firestore and Cloud Functions operated by Google. Google sign-in is optional. This web build does not include an advertising or analytics SDK; a separate inventory is still needed for the mobile app and any future integrations.</p><p>Authentication and technical service logs may include device, browser and network information processed by Google. Processing regions and any cross-border transfer details must be confirmed against the deployed Firebase configuration.</p></section>
        <section><h2>Community and AI conversations</h2><p>Your community name, username, invitation code and shared learning activity can be visible to other signed-in members. Your email is not included in that public community profile. Blocking records are private to your account; reports are not readable by other app users. AI conversations can be stored in your account.</p><p>When enabled, the AI mentor is available to adults who confirm they are 18 or older. Sending a question shares it and up to eight recent conversation messages with <a href="https://openrouter.ai/privacy" target="_blank" rel="noreferrer">OpenRouter</a>, which routes the request to <a href="https://www.modular.com/legal/privacy" target="_blank" rel="noreferrer">ModelRun (Modular)</a> to run Qwen3.8 27B. T1GER does not send your account identifier, email, learning profile or financial records to those providers. Anything you type in a question is part of the shared content, so keep personal, confidential and financial account information out of your questions.</p><p>T1GER records your adult declaration and provider notice version with daily mentor usage. This is a self-declaration, not age verification. Questions and replies can be saved in your private T1GER conversation history. Provider processing is governed by their policies; this notice does not promise that all intermediaries or technical logs have zero retention. Learners aged 15–17 can continue using lessons without this AI feature.</p></section><section><h2>Storage on your device</h2><p>Authentication uses browser storage needed to keep you signed in. Saved lesson artifacts, your focus timer, blocked-account cache, pending invitations and your light or dark preference can be stored locally in this browser. Clearing browser storage may remove those local details. No optional advertising tracker is included in this web build.</p></section>
        <section><h2>Retention and your choices</h2><p>Account and learning data remain while the service needs them to provide your account, subject to a retention and deletion schedule that must be finalized before publication. Profile offers a download of your Web learning profile and missions. This is not a complete service-wide data export. For a complete export, correction or deletion of your shared Web and mobile account, use the contact below. The request-handling and retention process must be finalized before launch.</p><p>For access, correction, export or deletion requests, contact <Contact/>. The rights and legal basis that apply depend on your location and must be specified in the final policy.</p></section>
        <section><h2>Age and updates</h2><p>T1GER is intended for people aged 15 and older. Do not create an account if you are under 15. Requirements for learners aged 15–17, including any parent or guardian permission, must be finalized before public release. T1GER will show an updated date when this notice changes.</p></section>
      </> : <>
        <section><h2>Service and accounts</h2><p>T1GER offers short learning experiences, exercises and memory reviews for people aged 15 and older. Do not create an account if you are under 15. A web account can share progress with the T1GER mobile app. Keep your sign-in details secure and provide accurate account information. Availability of particular paths can differ by platform.</p></section>
        <section><h2>Educational content</h2><p>Financial examples are educational simulations, not individualized investment advice, a recommendation to buy or sell, or a promise of future returns. Model assumptions, fees, taxes, inflation and investment risk matter. Do not use an example result as the sole basis for a financial decision.</p></section>
        <section><h2>Community and earned accessories</h2><p>Use community features respectfully. Do not harass others, impersonate someone or share private information. You can block an account or submit a report from community safety controls. Earned coins can unlock cosmetic accessories; these are not a real-money payment, cash balance or promise of monetary value. New Web challenges carry no coin stake and count server-verified missions.</p></section><section><h2>Your work and T1GER content</h2><p>You keep responsibility for the reflections and rules you enter. Do not submit sensitive financial information or content you do not have the right to use. T1GER’s original lesson design, text and visual presentation remain its content unless otherwise stated. External source links lead to their respective publishers.</p></section>
        <section><h2>Payments, changes and contact</h2><p>This web build does not take payments. Subscription status may be displayed from your existing T1GER account. Terms for paid products, account termination, governing law and dispute resolution require review before a public release. For questions, contact <Contact/>.</p></section>
      </>}
      <footer className="legal-foot"><a href={appHref('/')}>Return to T1GER</a><a href={appHref(privacy ? '/terms' : '/privacy')}>{privacy ? 'Read terms' : 'Read privacy notice'}</a></footer>
    </article>
  </main>;
}
