import React from 'react';
import { createRoot } from 'react-dom/client';
import '@fontsource/outfit/latin-400.css';
import '@fontsource/outfit/latin-500.css';
import '@fontsource/outfit/latin-600.css';
import '@fontsource/outfit/latin-700.css';
import '@fontsource/jetbrains-mono/latin-500.css';
import './style.css';
import './polish.css';
import './access.css';
import './experience.css';
import './design-system.css';
import './premium.css';
import './entry.css';
import App from './App';
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/react';
import { safeAnalyticsUrl } from '../../../src/lib/behaviorAnalytics';
import AppBoundary from './AppBoundary';

createRoot(document.getElementById('root')!).render(<React.StrictMode><AppBoundary><App /><Analytics beforeSend={event => ({ ...event, url: safeAnalyticsUrl(event.url) })}/><SpeedInsights beforeSend={event => ({ ...event, url: safeAnalyticsUrl(event.url) })}/></AppBoundary></React.StrictMode>);
