import { useEffect, useState } from 'react';
import { httpsCallable } from 'firebase/functions';
import { functions } from './firebase';
type Case={id:string;ticket?:string;category?:string;reason?:string;message?:string;details?:string;status?:string};
type Snapshot={support:Case[];reports:Case[];nextSupport:string|null;nextReports:string|null;mentor:{reservedCalls?:number;succeeded?:number;failed?:number};email:{reserved?:number}};
export default function Operations(){
  const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function load(older=false){if(!functions)return;setBusy(true);setError('');try{const next=(await httpsCallable<object,Snapshot>(functions,'t1gerOperations')({action:'list',...(older?{supportCursor:data?.nextSupport,reportsCursor:data?.nextReports}:{})})).data;setData(previous=>older&&previous?{...next,support:previous.nextSupport?[...previous.support,...next.support]:previous.support,reports:previous.nextReports?[...previous.reports,...next.reports]:previous.reports,nextSupport:previous.nextSupport?next.nextSupport:null,nextReports:previous.nextReports?next.nextReports:null}:next);}catch{setError('Operator access is required. Sign in with an account explicitly authorized by the server.');}finally{setBusy(false);}}
  useEffect(()=>{
    if(!functions)return;let active=true;setBusy(true);
    httpsCallable<object,Snapshot>(functions,'t1gerOperations')({action:'list'}).then(result=>{if(active)setData(result.data);}).catch(()=>{if(active)setError('Operator access is required. Sign in with an account explicitly authorized by the server.');}).finally(()=>{if(active)setBusy(false);});
    return()=>{active=false;};
  },[]);
  return <main className="page operations-page ph-no-capture"><header className="page-top"><p className="eyebrow">OPERATIONS / PRIVATE</p><h1>Keep T1GER running.</h1><a className="text-link" href="/app/learn">Return to learning</a></header>{error && <p role="alert" className="error">{error}</p>}<button className="button subtle" disabled={busy} onClick={()=>void load()}>{busy?'Loading…':'Refresh'}</button>{data && <><div className="metric-strip"><div><strong>{data.mentor.succeeded||0}</strong><span>mentor replies today</span></div><div><strong>{data.mentor.failed||0}</strong><span>provider failures</span></div><div><strong>{data.mentor.reservedCalls||0}</strong><span>reserved provider calls</span></div><div><strong>{data.email.reserved||0}</strong><span>reserved email attempts</span></div></div>{([['supportRequests','Support and privacy requests',data.support],['reports','Community reports',data.reports]] as const).map(([collection,title,cases])=><section className="settings-section" key={collection}><h2>{title}</h2><p>Cases load in pages of 50. Keep requests open until the action is completed.</p>{cases.length?cases.map(item=><article className="operation-case" key={item.id}><strong>{item.ticket || item.id}</strong><p>{item.category || item.reason} · {item.status || 'open'}</p><p className="saved-summary">{item.message || item.details}</p>{item.status!=='resolved' && <button className="button subtle" disabled={busy} onClick={async()=>{if(!functions)return;setBusy(true);try{await httpsCallable(functions,'t1gerOperations')({action:'resolve',collection,id:item.id});setData(previous=>previous?{...previous,[collection==='supportRequests'?'support':'reports']:(collection==='supportRequests'?previous.support:previous.reports).map(entry=>entry.id===item.id?{...entry,status:'resolved'}:entry)}:previous);}catch{setError('Could not resolve the case. Retry.');}finally{setBusy(false);}}}>Mark resolved</button>}</article>):<p>No cases yet.</p>}</section>)}{(data.nextSupport || data.nextReports) && <button className="button subtle" disabled={busy} onClick={()=>void load(true)}>Load older cases</button>}</>}</main>;
}
