const assert=require('node:assert/strict'),crypto=require('node:crypto');
if(!process.env.FIRESTORE_EMULATOR_HOST || !process.env.FIREBASE_AUTH_EMULATOR_HOST)throw new Error('This contract only runs in disposable emulators.');
const {initializeApp}=require('firebase-admin/app');initializeApp({projectId:'demo-t1ger-web'});
const {getAuth}=require('firebase-admin/auth'),{getFirestore}=require('firebase-admin/firestore');
const client=require('../../../apps/web/node_modules/firebase/app'),fa=require('../../../apps/web/node_modules/firebase/auth'),ff=require('../../../apps/web/node_modules/firebase/firestore'),fn=require('../../../apps/web/node_modules/firebase/functions');
const {acquireMentor}=require('../lib/mentorAdmission.js'),{verifyEmailWebhook}=require('../lib/learningEmails.js');
(async()=>{
 const admin=getFirestore(),global=admin.doc('operations/mentor-'+new Date().toISOString().slice(0,10));await global.set({leases:{},reservedCalls:0,openUntil:0});
 const uid='admission-'+crypto.randomUUID();const lease=await acquireMentor(uid,10,'test');
 await assert.rejects(()=>acquireMentor(uid,10,'test'),e=>e.details?.reason==='cooldown');
 const other=await Promise.all([1,2,3].map(i=>acquireMentor(uid+i,10,'test')));
 await assert.rejects(()=>acquireMentor(uid+'overflow',10,'test'),e=>e.details?.reason==='busy');
 await Promise.all([lease,...other].map(release=>release(false)));
 assert.equal(Object.keys((await global.get()).data().leases).length,0,'release must replace the lease map');
 for(let i=0;i<3;i++)await (await acquireMentor(uid+'failure'+i,10,'test'))(true);
 await assert.rejects(()=>acquireMentor(uid+'circuit',10,'test'),e=>e.code==='unavailable');
 console.log('PASS: transactional global quota, exclusive leases, cooldown and provider circuit.');
 const app=client.initializeApp({projectId:'demo-t1ger-web',apiKey:'demo-key',authDomain:'localhost'},'launch-contract');
 const auth=fa.getAuth(app);fa.connectAuthEmulator(auth,'http://127.0.0.1:9099',{disableWarnings:true});
 const db=ff.getFirestore(app);ff.connectFirestoreEmulator(db,'127.0.0.1',8080);
 const functions=fn.getFunctions(app);fn.connectFunctionsEmulator(functions,'127.0.0.1',5001);
 const learner=await fa.createUserWithEmailAndPassword(auth,`launch-${crypto.randomUUID()}@example.invalid`,'Emulator-only-2026!');
 const call=(name,data)=>fn.httpsCallable(functions,name)(data);
 const prefs={enabled:true,reminders:true,weekly:true,milestones:true,language:'es',timeZone:'America/New_York',hour:18};
 await assert.rejects(()=>call('learningEmailPreferences',{action:'save',preferences:prefs}),e=>e.code==='functions/failed-precondition');
 await getAuth().updateUser(learner.user.uid,{emailVerified:true});
 await learner.user.reload();await learner.user.getIdToken(true);
 const saved=await call('learningEmailPreferences',{action:'save',preferences:prefs});assert.equal(saved.data.preferences.enabled,true);assert.equal(saved.data.ready,false);
 await assert.rejects(()=>ff.getDoc(ff.doc(db,'emailPreferences',learner.user.uid)),e=>e.code==='permission-denied');
 const request={category:'support',message:'Disposable emulator support request only.',requestId:crypto.randomUUID()};
 const first=await call('createSupportRequest',request),retry=await call('createSupportRequest',request);assert.equal(first.data.ticket,retry.data.ticket);
 await assert.rejects(()=>call('t1gerOperations',{action:'list',t1gerOperator:true}),e=>e.code==='functions/permission-denied');
 await assert.rejects(()=>ff.getDocs(ff.collection(db,'supportRequests')),e=>e.code==='permission-denied');
 await getAuth().setCustomUserClaims(learner.user.uid,{t1gerOperator:true});await learner.user.getIdToken(true);
 const queue=await call('t1gerOperations',{action:'list'});assert(queue.data.support.some(x=>x.ticket===first.data.ticket));
 const batch=admin.batch();for(let i=0;i<55;i++)batch.set(admin.doc(`supportRequests/page-${i}`),{createdAt:Date.now()+i,status:'open',message:'Disposable pagination fixture'});await batch.commit();
 const page1=await call('t1gerOperations',{action:'list'});assert.equal(page1.data.support.length,50);assert(page1.data.nextSupport);
 const page2=await call('t1gerOperations',{action:'list',supportCursor:page1.data.nextSupport});assert.equal(page2.data.support.length,6);assert.equal(new Set([...page1.data.support,...page2.data.support].map(x=>x.id)).size,56);
 await call('t1gerOperations',{action:'resolve',collection:'supportRequests',id:page1.data.support[0].id});assert.equal((await admin.doc('supportRequests/'+page1.data.support[0].id).get()).data().status,'resolved');
 const token=(await admin.doc(`emailPreferences/${learner.user.uid}`).get()).data().unsubscribeToken;
 const url=`http://127.0.0.1:5001/demo-t1ger-web/us-central1/emailUnsubscribe?t=${token}`;
 assert.equal((await fetch(url)).status,200);assert.equal((await admin.doc(`emailPreferences/${learner.user.uid}`).get()).data().enabled,true,'GET scanners must not unsubscribe');
 assert.equal((await fetch(url,{method:'POST'})).status,200);assert.equal((await admin.doc(`emailPreferences/${learner.user.uid}`).get()).data().enabled,false);
 const raw=Buffer.from('{"type":"email.delivered"}'),secret='whsec_'+crypto.randomBytes(32).toString('base64'),timestamp=String(Math.floor(Date.now()/1000)),id='test-event';
 const signature=crypto.createHmac('sha256',Buffer.from(secret.slice(6),'base64')).update(`${id}.${timestamp}.`).update(raw).digest('base64');
 const headers={'svix-id':id,'svix-timestamp':timestamp,'svix-signature':'v1,'+signature};
 assert.equal(verifyEmailWebhook(raw,headers,secret),true);assert.equal(verifyEmailWebhook(Buffer.from('{}'),headers,secret),false);assert.equal(verifyEmailWebhook(raw,headers,secret,Date.now()+600000),false);
 console.log('PASS: verified email opt-in, private preferences and support, ticket dedup, operator authorization, unsubscribe and webhook signature.');
 await client.deleteApp(app);process.exit(0);
})().catch(e=>{console.error(e.code||e.message);process.exit(1);});
